# Generated by Django 5.2.15 on 2026-07-03 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='نام و نام خانوادگی')),
                ('job_title', models.CharField(max_length=100, verbose_name='عنوان شغلی')),
                ('bio', models.TextField(verbose_name='درباره من')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('phone', models.CharField(max_length=20, verbose_name='شماره تماس')),
                ('address', models.CharField(max_length=255, verbose_name='آدرس')),
                ('birthday', models.DateField(verbose_name='تاریخ تولد')),
                ('avatar', models.ImageField(upload_to='avatars/', verbose_name='تصویر پروفایل')),
            ],
        ),
    ]
