# Generated by Django 5.2.10 on 2026-09-06 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_education_experience_languagecertificate_profile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='description_fa',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='education',
            name='institution_fa',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='education',
            name='title_fa',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='experience',
            name='description_fa',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='experience',
            name='title_fa',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='languagecertificate',
            name='institution_fa',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='languagecertificate',
            name='level_fa',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='languagecertificate',
            name='title_fa',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='bio_fa',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='profile',
            name='title_fa',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='programminglanguage',
            name='name_fa',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='programminglanguage',
            name='technologies_fa',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='project',
            name='description_fa',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='project',
            name='live_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='title_fa',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='projectcategory',
            name='name_fa',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='skill',
            name='description_fa',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='skill',
            name='name_fa',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='skillcategory',
            name='name_fa',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
